export enum FirestoreCollecionName {
  PROJECTS = 'projects',
  USERS = 'users',
  NEGOTIATIONS = 'negotiations',
  PRODUCTS = 'products',
  PRODUCT_TYPES = 'product-types',
  EQUIVALENT_AREAS = 'equivalent-areas',
  EQUIVALENT_AREA_TYPES = 'equivalent-area-types',
  CURVE_MODEL_TYPES = 'curve-model-types',
  BUDGETS = 'budgets',
  CHRONOGRAMS = 'chronograms',
  COMMERCIALIZATIONS = 'commercializations',
  INCORPORATION_COSTS = 'incorporation-costs',
  ESTATE_AGENCY_REMUNERATION_TYPES = 'estate-agency-remuneration-types',
  MARKETINGS = 'marketings',
  TAX_TYPES = 'tax-types',
  TAXES = 'taxes',
  FINANCING_TYPES = 'financing-types',
  CROWDFUNDINGS = 'crowdfundings',
  GROUPS = 'groups',
  SUBGROUPS = 'subgroups',
  ACTIVITIES = 'activities',
  SUPPLIERS = 'suppliers',
  SUMMARY_PROJECTS = 'summary-projects',
  STATUS_TYPES = 'status-types',
  VIABILITIES = 'viabilities'
}
